homeassistant:
  customize:
    package.node_anchors:
      router: &router binary_sensor.fritz_box_6890_lte_connection

##############################################################
#         DA QUESTO PUNTO NON MODIFICARE
##############################################################

automation:
  - alias: "Allarme: Stato Internet"
    id: allarme_internet_state
    trigger:
      - platform: state
        entity_id: *router
    action:
      - alias: INVIA NOTIFICA
        event: customizations
        event_data:
          types: notify_alarm
          notify: stato_router
          tag: stato_router
          title: --CONNESSIONE--
          message: >-
            {% if trigger.to_state.state == 'on' %} 
              {{ 'Connessione internet tornata a funzionare alle ' + as_local(states[trigger.entity_id].last_changed).strftime("%H:%M") }}
            {% else %} 
              {{ 'Connessione Assente attivo fallback LTE dalle ' + as_local(states[trigger.entity_id].last_changed).strftime("%H:%M") }}
            {% endif %}
